### ISSUE TITLE
topo sort of context entries is impossible

### ISSUE THREAD

**Issue by konstantinosKokos** [omelkonian/agda2train#12]
unlike scope entries, context entries are nameless, so there's no way to resolve reference hierarchies 

related note: telescope is supposed to be a list of named types, but there's a field clash between "name" in the context of a scope entry and in the context of a scope reference

**Comment by omelkonian** [comment]
The related note is a good catch, now fixed by not using `"name"` for everything, instead:
- `"refName"` holding the identifier of a `ScopeReference`
- `"boundName"` holding the bound variable name of a `Pi`

Note that you cannot properly build a dependency tree out of those strings/names, these are not unique in contrast to the scope that has fully-qualified names (+ unique numeric identifiers), so you have to really use the DeBruijn indices to actually calculate which context entry a local variable refers to, c.f. [`Test.ContextShadowing{.agda/.json}`](https://github.com/omelkonian/agda2train/blob/725a959b4c53c722cf451d1cac43bf15267c9602/test/Test/ContextShadowing.agda) for a detailed example.
